src/color.rs

Need this for my own debugging purposes, and I'm sure this tiny change would be helpful to others in formatting objects containing RGB items

add Debug to color structs

---

src/hal/font.rs

Hello, i found that fonts not checked for format, so when you trying to png in RGBA, for example, you got mess on screen instead of image. I added some simple format choosing and panic message to make it clear for user. I am not tested it for wasm target, but code looks same.

choose font image format or panic

---

src/fieldofview.rs

I suspect low-res nature of this is what's causing the duplication of points since a `Point` can appear on two different FoV lines if the two lines are close enough (which is often the case!). The overlap in scan ranges in `field_of_view` was also contributing to this problem, so I changed it so they aren't overlapping anymore, and moved the HashSet there for deduplication. I've tested it on my end and it seems to be working properly now.

Adjusted scan range and relocated HashSet

---

Cargo.toml
benches/fov_benchmark.rs
src/fieldofview.rs

Adds a benchmark for FOV calculation and introduces some optimizations. See commit messages for opt details.
Each optimization step has been benchmarked to ensure it's actually an improvement.
Total improvement is about ~14x for FOV with range 8, and about 27x improvement for FOV with range 20.
Note: The benchmark creates a new random map for each iteration, instead of using a static map. This causes some 5-7% variance in runtimes between benchmark iterations. This should be fixed if we want to do further optimization, since the low hanging fruit is probably all gone now.

Optimize field of view

---

src/hal/native/mainloop.rs

Hi! I believe this fixes #46 . Tested on a retina MacBook (so, a constant scale factor of 2.0). Would be great if someone could test on HiDPI Linux or Windows as well!

Pull Request: Fix initial viewport setting on hidpi screens

---

src/hal/native/mainloop.rs

Also removes the use of the deprecated modifiers field in event::KeyboardInput
With this change shift/ctrl/alt will remain true until the modifier keys are depressed. If one wants to only act when the modifier is pressed, one can chose to act only when Rltk::key is VirtualKeyCode::SHIFT_L etc or simply only check shift/ctrl/alt whe Rltk::key is Some(_).

Breaking change: Make Rltk::shift/ctrl/alt modifiers sticky

---

src/geometry/point3.rs
src/geometry/rect.rs

There are three `impl specs::prelude::Component for Point`.
It occurs some build errors with feature `ecs`.
This PR fix above build errors.

fix ecs feature build failure

---

src/pathfinding/dijkstra.rs

`pathfinding/dijkstra.rs` contains alternative implementation for threading.
These implementation have not same type as basic implementation.
It means, some build errors happen with feature `threaded`.
This PR fix above build errors.

fix threaded feature build failure

---

src/fieldofview.rs
src/geometry/circle_bresenham.rs
src/geometry/mod.rs
src/lib.rs

Added a version of the Bresenham circle algorithm that does not jump in x and y simultaneously. Replacing with this algorithm version in the field of view calculation solves an issue where points just inside diagonal jumps in the circle would not be included.

Bresenham circle without diagonal jumping

---

Cargo.toml
src/color.rs
src/geometry/point.rs
src/geometry/point3.rs
src/geometry/rect.rs

In Rust Library Team's API guideline (It is semi-standard),
To get good interoperability,
we need to use serialization feature as name as `serde`.
see also:
https://rust-lang.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde
and, more small thing, `serde_json` didn't used in rltk_rs.
Maybe, this crate should use in user code, not rltk_rs.
And renaming `serialization` feature is little bit hard if the `serde_json` dependency be. So I dropped the dependency.
Discuss:
Maybe, currently, I guess, there're no active user about `serialization` feature.
Because,  the code had broken before #50 is merge.
So I think, It is a chance to fix this issue.

Fit to api guideline: rename serialization feature

---

.github/workflows/rust.yml

Hello!  This adds basic CI building, testing, checking benchmarks, and checking examples for Linux, Macos, and Windows. I ran into some issues getting pieces of it passing immediately and deleted them for now.
Azure pipelines, travis, and other CI providers are also free for FOSS projects, they have ups and downs.  One thing I find really frustrating about github actions is finding documentation about doing basic things (like installing ncurses).  Less abstract CI providers make that kind of thing a lot simpler in my opinion.  But the nice thing about CI is that once it's set up, you usually don't have to touch it too much.
It's also often a good idea to run `cargo check` with all combinations of features that you want to support!
Here's some of the stuff I had to disable (this doesn't …

Add basic GitHub Actions CI

---

benches/batching_benchmark.rs
examples/ex01-helloworld.rs
examples/ex02-sparse.rs
examples/ex03-walking.rs
examples/ex04-fov.rs
examples/ex05-dijkstra.rs
examples/ex06-astar-mouse.rs
examples/ex07-tiles.rs
examples/ex08-rex.rs
examples/ex09-offsets.rs
examples/ex10-postprocess.rs
examples/ex11-random.rs
examples/ex12-simplex.rs
examples/ex13-textblock.rs
examples/ex14-dwarfmap.rs
examples/ex15-specs.rs
examples/ex16-keyboard.rs
src/hal/amethyst_be/init.rs
src/hal/amethyst_be/mod.rs
src/hal/curses/mod.rs
src/hal/dummy/mod.rs
src/hal/native/init.rs
src/hal/native/mod.rs
src/hal/wasm/init.rs
src/hal/wasm/mod.rs
src/initializer.rs
src/lib.rs
src/rltk.rs

This retains the existing initialization interface, other than a new `platform_hints` option on `init_raw` (which very few things use). It also offers a new builder-based initialization, so you can initialize with the much-easier-to-read:
```rust
let context = RltkBuilder::simple80x50()
.with_title("Hello RLTK World")
.build();
```
Or a more complex example:
```rust
let context = RltkBuilder::simple80x50()
// Then we register the 8x16 VGA font. This is embedded automatically, so you can just use it.
.with_font("vga8x16.png", 8, 16)
// Next we want a "sparse" (no background) console, of half the height since its an 8x16 font.
.with_sparse_console(80, 25, "vga8x16.png")
// And a window title
.with_title("RLTK Example 2 - Sparse Consoles")
// And call the build function to actually obtain …
```

Initialization branch merge

---

bracket-terminal/src/hal/wasm/font.rs
bracket-terminal/src/hal/wasm/init.rs
bracket-terminal/src/hal/wasm/mainloop.rs
bracket-terminal/src/hal/wasm/simple_console_backing.rs
bracket-terminal/src/hal/wasm/sparse_console_backing.rs
bracket-terminal/src/simple_console.rs

I had to make these changes for the WASM target to compile.
I still can't get any example to run on WASM target. I've got following error in the browser's console :
`TypeError: import object field '__wbindgen_placeholder__' is not an Object`

fix wasm compilation

---

bracket-terminal/examples/benchmark.rs

This example make it possible to easily compare rendering performance between different backend.
It's nice to store the values somewhere to be able to detect performance regressions from one version to another.
Since the example produces the exact same output as the doryen-rs perf example, it also helps measuring the overhead of using doryen-rs on top of bracket-lib instead of using directly bracket-lib.
Finally, it helps comparing bracket-lib performance with doryen-rs's current unrust backend.

render benchmark example

---

bracket-pathfinding/Cargo.toml
bracket-pathfinding/examples/dijkstra/main.rs
bracket-pathfinding/src/dijkstra.rs
bracket-pathfinding/src/lib.rs

See https://github.com/thebracket/bracket-lib/issues/103
* Fix dijkstra map building. It was building incorrect maps before.
* Removed all usages of unsafe, as the speedy clearing of buffers isn't necessary with the new algorithm.
* Change the dijkstra example code to better show the flow
* Make the threaded version **not** also run the unthreaded version at the same time
* Arbitrarily run threaded version if there are 4 or more starts. This might be a bad idea, see below.
The algorithm used **probably** ensures there are no re-visits of nodes when run single threaded. Should just be BFS with a single start, and lockstepped BFSes with multiple starts. Most of the time in the build functions is spent in calls to `get_available_exits`. The single threaded version should call this at most …

Fix threaded and unthreaded dijkstra map

---

bracket-terminal/src/lib.rs

Adding additional constraints for Error type would allow to easily convert from `bracket-lib::Error` to `anyhow::Error` like so:
```rust
let context = BTermBuilder::simple80x50()
.with_title("Title")
.build()
.map_err(|e| anyhow!(e))?;
```

Make error type compatible with anyhow lib

---

bracket-geometry/Cargo.toml

Requires ultraviolet 0.4.6, which relies on wide.
wide broke its API to fix incorrect math, breaking ultraviolet (and thus bracket) builds.
~ sets a minimum ver but allows accepting patch progress without new releases.
Closes #119.
alternative solutions:
fork ultraviolet and depend on your fork, with a hard-pinned wide dep instead of soft-pinned like this, but now you have to update manually to accept patches. Seems like effort.

Accept new ultraviolet patches

---

Cargo.toml
rltk/Cargo.toml

This makes more sense if you've read #120 first.
I would not normally offer such a PR because while the dep on ultraviolet needs to be fixed, this feels more like dictating a release strategy. So I do so as a separate PR because I realize you might not care for such a recommendation, but I do so anyways in spite of the vague feeling it is overly forward because I realize that your extreme busy-ness might mean that you appreciate such a recommendation and everything being set up so you just have to hit the button. So, please feel free to accept or reject as you please.
This implements all the changes to allow rltk to passively (without a release) accept the patches from bracket-lib which would accept the patches from bracket-geometry which would accept the patches from ultraviolet which …

Prep 0.8.1 to allow self-patches

---

bracket-algorithm-traits/src/algorithm2d.rs
bracket-algorithm-traits/src/algorithm3d.rs
bracket-pathfinding/src/fieldofview.rs

Fixes #116: when a point with a zero-coordinate was considered as not in bounds for map algorithms. The bug is the root cause of the problem that zero-coordinate points are always not visible.

Consider zero point as in bounds for algorithms.

---

bracket-random/src/iterators.rs

Prior to this change, the following code is accepted by the Rust compiler:
```rust
use bracket_random::prelude::*;
fn make_bad() -> DiceIterator {
DiceIterator::new(10, &mut RandomNumberGenerator::new())
}
fn main() {
let dice = make_bad();
let res = dice.zip(0..100).collect::<Vec<_>>();
println!("Results: {:?}", res)
}
```
It clearly exhibits undefined behavior, dereferencing a pointer to a `RandomNumberGenerator` that doesn't live long enough.
In testing that snippet, I did the following:
I built and ran it in debug mode, which printed the vector of results that might be expected.
I built and ran it in release mode, which segfaulted.
`Segmentation fault (core dumped)`
I ran it with Miri, which spat out a long error message. This is the important part:
```
Undefined Behavior: pointer to …
```

remove bad unsafe usage

---

bracket-noise/src/fastnoise.rs

Under the hood, `.to_bits()` does transmute, but this makes it easier to grep for `unsafe` to audit in this project.

Replace unsafe code with exactly equivalent safe code

---

bracket-terminal/src/input/input_handler.rs

Fixes #66  
The reason why modifier keys don't work is their state is reset in clear_input_state() called on Event::NewEvents every tick.  
This PR removes the lines that reset the states.

Fix modifier keys

---

src/lib.rs

The crate felt really messy on the documentation side of things with everything being namespaced in prelude only (especially with the color const's) so I just added some modules in the root to split things up a bit and make it more readable and more inline with most rust crates setup.

moved all crates into separate modules in bracket-lib/lib.rs

---

bracket-pathfinding/benches/astar_benchmark.rs

valid_exit() in the benchmark will receive negative x and y deltas
from get_available_exist() which when the point they are examining a loc
which is x=0 or y=0 would create a negative search position.  This in
turn would panic in algorithm2d when trying to coerce them into usize.

Makes astar benchmark run.

---

bracket-terminal/src/hal/native/init.rs

Removes `std::env::set_var("WINIT_UNIX_BACKEND", "x11")` which breaks support on pure Wayland environments that have no x11 capabilities.
Fixes #161

stop forcing WINIT_UNIX_BACKEND env var to fix wayland

---

bracket-pathfinding/src/fieldofview.rs

The old algorithm caused holes within the visibility field when range
was 6. With a wall above the player (in the middile) the result was like this:

Improve FoV algorithm when range=6

---

bracket-terminal/src/hal/native/mainloop.rs

Only the bottom left corner was shown in screenshots on  HiDPI X11 screens.

Fix dpi-scale for screenshots

---

bracket-terminal/src/hal/gl_common/backing/sprite_console_backing.rs

This should fix the issue with `cls()` not actually clearing the console if nothing is then rendered on it.
This applies a fix similar to the one found in #117, but for the sprite console instead of the sparse console.

Remove sprites.is_empty() Check

---

bracket-terminal/src/rex.rs

Possibly there's a way to DRY these functions with some common trait, but at a glance I couldn't find one.

Add xp_to_draw_batch, to the tune of xp_to_console

---

bracket-random/src/random.rs

Because the `rand` crate provides tons of useful traits / algorithms (eg. shuffling vectors) that require a `rand`-flavored RNG.
(Also, `rustfmt` and doc comments `//` -> `///` while we're at it)

Expose underlying RNG object from RandomNumberGenerator

---

bracket-terminal/src/bterm.rs
bracket-terminal/src/hal/native/mainloop.rs

#109 Replace the scaling/mouse position code with something a lot more robust. It *should* work with scaling, but I don't have any projects that use it. Tested on Ubuntu/X11 and Windows with various display scaling settings. Needs testing on a Mac.

Simpler scaling

---

bracket-geometry/src/distance.rs

⚠️ First Rust PR. May contain newbity. ⚠️ 
This PR adds Copy and Clone to DistanceAlg.
Suppose a user function creates a map builder, specifying a distance algorithm to be used within.
```
struct Builder {
pub distance_algorithm: DistanceAlg;
};
```
The builder would ideally be able to employ the algorithm without having to match against all known distance algorithms:
```
impl Builder {
fn build(&self, ...) {
...
let distance = self.distance_algorithm.distance_2d(origin, destination);
}
}
```
However, if `distance_algorithm` ends up behind a shared reference, and does not implement Copy, the caller must do this instead:
```
impl Builder {
fn build(&self, ...) {
...
let distance = match self.distance_algorithm {
DistanceAlg::Pythagoras => DistanceAlg::Pythagoras::distance_2d(origin, …
```

Feature: make bracket-geometry distance algorithms copyable

---

bracket-terminal/src/hal/curses/main_loop.rs

Provided recognition of several key codes, as reported in issue #207
The "Escape" seems to be handled differently, and is still not being recognized.

Updated some key codes

---

bracket-terminal/Cargo.toml
bracket-terminal/src/hal/gl_common/shader.rs
bracket-terminal/src/hal/native/init.rs
bracket-terminal/src/hal/native/mainloop.rs

The version of glow that bracket-lib was using depended on a yanked version of `slotmap`.  This updates glow to the most recent version.
Please see https://github.com/grovesNL/glow/issues/179 for the instigating report.

update glow dependency

---

bracket-terminal/examples/batch_z_order.rs
bracket-terminal/src/consoles/command_buffer.rs
bracket-terminal/src/hal/gl_common/framebuffer.rs

FIXES #225 In-batch z-order is now supported, with a series of `with_z` functions for draw batches. Includes an example.

Issue 225 z order

---

bracket-terminal/src/hal/wasm/init.rs

FIXES #251 `screen_scaler` now properly initialized on WASM backend.
Because `screen_scaler` is never initialized properly, `self.logical_size` is `(0, 0)`.
So when `calc_step` is called:
https://github.com/amethyst/bracket-lib/blob/4b475077ccf3bd67d196dfed94d4d719118934a2/bracket-terminal/src/hal/gl_common/backing/simple_console_backing.rs#L117
(which in turn executes)
https://github.com/amethyst/bracket-lib/blob/4b475077ccf3bd67d196dfed94d4d719118934a2/bracket-terminal/src/hal/scaler.rs#L213-L214
Here, we have a divide by zero.
https://github.com/amethyst/bracket-lib/blob/4b475077ccf3bd67d196dfed94d4d719118934a2/bracket-terminal/src/hal/scaler.rs#L196-L197
The result is `NaN` for `step_x` and `step_y`

#251 - Initialize screen_scaler for wasm backend

---

bracket-bevy/src/consoles/update_system.rs

Whenever the window is closed, or the close_on_exit system is used, bevy closes all windows then sends the `AppExit` event to shutdown the application. During that time, the systems still run, like our mouse_update system which causes errors on unwrapping of the current window. This just adds a check to see if the window exist.
This is my first ever PR to another repo so I don't really know how to structure this or if I even did a decent job (rust noob here) so any feedback is welcome!

check if window is active before processing

---

bracket-pathfinding/src/astar.rs

This pull request fixes an error in the A* implementation and adds two separate test cases to prevent the issue I was facing in the future.
Fixes #267 
The A* implementation previously used these formulas to calculate the new g and f values for a node:
```
successor.g = previous.f + step_cost
successor.f = previous.f + step_cost + distance_to_end
```
The correct equations however use the `previous.g` value instead. See [here](https://en.wikipedia.org/wiki/A*_search_algorithm#Pseudocode), [here](https://gist.github.com/jcward/45afd22560939aaae5c75e68f1e57505#summary-of-the-a-method), or [here](https://www.redblobgames.com/pathfinding/a-star/implementation.html#cpp-astar) for reference.
`g` is the cost to reach the node from the start, `f` is `g` plus a heuristic for the remaining cost to …

Use g value instead of f value to create sucessors in A*

---

bracket-terminal/src/bterm.rs
bracket-terminal/src/hal/crossterm_be/init.rs
bracket-terminal/src/hal/curses/init.rs
bracket-terminal/src/hal/native/init.rs
bracket-terminal/src/hal/native/mainloop.rs
bracket-terminal/src/hal/wasm/init.rs
bracket-terminal/src/hal/webgpu/init.rs

I added the ability to set the mouse cursor visibility on opengl so the user can do things like build a software cursor. The user can change the visibility by either manually setting a bool in the BTerm context called mouse_visibility or by using `ctx.with_mouse_visibility(false);`. I wasn't able to figure out how to get it to work on wgpu or crossterm as the library won't compile on my system when using those backends. I don't think it's possible to set the cursor visibility on curses, so on backends other than native gl the variable and the function do nothing.

Added ability for the user to enable or disable the mouse cursor when using the native gl backend

---

bracket-noise/src/fastnoise.rs

I have been building a small 'procedural map generation app' based on your awesome tutorial @thebracket. While working on allowing the user to configure the various 'map builders' I came across the issue that the `enum`s in the `bracket_noise` library do not implement the `Debug` trait so I went ahead and added `derive`s for them to be able to use these types in structs that want to derive Debug themselves.
I would be honored and happy if you accepted the PR. Thanks for the great content you are producing - both your RLTK tutorial and the book are awesome and inspiring, keep up the good work!

Derive Debug trait for enums used in fastnoise module

---

bracket-terminal/examples/flexible.rs

I think I've picked up a duplicate line in the flexible console example.
This removes it :)

Remove duplicate call to post scanlines processing

---

bracket-terminal/src/hal/gl_common/backing/shared_main_loop.rs

I think the expected behavior is that a `SpriteConsole` has a sprite_sheet idx and uses this to render from the correct `SpriteSheet` from `BTermInternal.sprite_sheets`. Currently though the code in `bracket-terminal/src/hal/gl_common/shared_main_loop.rs` will only ever pull from the first sprite sheet. The change I provide here gets the correct sprite sheet idx from the `SpriteConsole` so that it will render the correct sprite.
Minimal case for reproduction:
```rust 
use bracket_terminal::prelude::*;
struct State;
impl GameState for State {
fn tick(&mut self, ctx: &mut BTerm) {
ctx.set_active_console(0); // The console that registered the sprite_dood
ctx.cls(); // Clear console 0
ctx.add_sprite(Rect::with_size(1, 1, 64, 64), 0, RGBA::from_f32(1.0, 1.0, 1.0, 1.0), 0); …
```

Get SpriteConsole's sprite sheet when rendering sprite

---

bracket-terminal/src/consoles/flexible_console.rs

Fixes #278 
The tiles are not cleared on each tick so they keep incrementing, causing the app to slow down.
This clears the tiles on each tick and maintains the previous fix for #278. Forcing a new tile after clearing, redraws all tiles. It's not elegant and I'm still looking into this. 
Before (excuse the gif rendering issue)
After (excuse the gif rendering issue)

Fix tiles incrementing each frame

---

bracket-geometry/src/line_bresenham.rs

- Add advance method on Bresenham that return the next point without checking if we are past end. Bresenham iterator use this internally. It could also be used to create infinite line
- Add BresenhamInclusive which is a wrapper over Bresenham that also return the end point
- Add BresenhamInclusive to most tests
No breaking change

Add new bresenham iterator that yield end point

---

Cargo.toml
bracket-color/Cargo.toml
bracket-color/examples/util/mod.rs
bracket-color/src/lib.rs

Publish color mods separately (in addition to prelude) to make it easier to specifically use parts of the library.

re-export color mods separately

---

bracket-pathfinding/src/dijkstra.rs

I used `threaded` feature and it threw some errors so this is removing the duplicated function. There is also a missing function `build_parallel_weighted`

remove duplicate parellel function

---

Cargo.toml
bracket-bevy/Cargo.toml
bracket-geometry/Cargo.toml
bracket-geometry/src/point.rs
bracket-geometry/src/point3.rs
rltk/Cargo.toml

With Bevy becoming increasingly popular, I thought we could add it to the component tree like specs
I chose TableStorage as the default storage type. Sparse-set is also available (https://bevy-cheatbook.github.io/patterns/component-storage.html#table-storage) but this seems like a specific use case. It might fit our use case since Point could be inserted quite frequently

add point to bevy component ecs
